# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buildGraularUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image_rc

class Ui_buildGraular(object):
    def setupUi(self, buildGraular):
        buildGraular.setObjectName("buildGraular")
        buildGraular.resize(517, 677)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        buildGraular.setFont(font)
        buildGraular.setStyleSheet("")
        self.label = QtWidgets.QLabel(buildGraular)
        self.label.setGeometry(QtCore.QRect(40, 30, 141, 61))
        self.label.setStyleSheet("#label{\n"
"    border-radius:4px;\n"
"    background-color: transparent;\n"
"    font: 18pt \"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.label.setObjectName("label")
        self.textCount = QtWidgets.QTextEdit(buildGraular)
        self.textCount.setEnabled(False)
        self.textCount.setGeometry(QtCore.QRect(200, 30, 91, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.textCount.setFont(font)
        self.textCount.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px\n"
"")
        self.textCount.setObjectName("textCount")
        self.label_2 = QtWidgets.QLabel(buildGraular)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 151, 50))
        self.label_2.setStyleSheet("#label_2{\n"
"    border-radius:4px;\n"
"    background-color: transparent;\n"
"    font: 18pt \"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.textViewDiv = QtWidgets.QTextEdit(buildGraular)
        self.textViewDiv.setGeometry(QtCore.QRect(190, 120, 271, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.textViewDiv.setFont(font)
        self.textViewDiv.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px\n"
"")
        self.textViewDiv.setObjectName("textViewDiv")
        self.top = QtWidgets.QFrame(buildGraular)
        self.top.setGeometry(QtCore.QRect(0, 0, 531, 681))
        self.top.setStyleSheet("  background-image: url(:/images/bg3.jpg);\n"
"  background-position: center;")
        self.top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.tabCi = QtWidgets.QToolBox(self.top)
        self.tabCi.setGeometry(QtCore.QRect(20, 210, 461, 451))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.tabCi.setFont(font)
        self.tabCi.setMouseTracking(True)
        self.tabCi.setStyleSheet("*{\n"
"background-color: transparent;\n"
"}\n"
"QTabWidget::tab-bar { \n"
"    alignment: center; \n"
"} \n"
"QTabBar::tab:hover{ \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: transparent;\n"
"}\n"
"QTabWidget::pane{ \n"
"    border:none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(0, 0, 0); /* 标签页背景颜色 */\n"
"    font-family: 微软雅黑; /* 标签页字体类型 */\n"
"    font-size: 24px; /* 标签页字体大小 */\n"
"    color: rgb(255, 255, 255); /* 标签页字体颜色 */\n"
"    padding: 10px; /* 内边距 */\n"
"    border: 1px solid rgb(150, 150, 150); /* 边框 */\n"
"    border-top-left-radius: 5px; /* 左上角圆角 */\n"
"    border-top-right-radius: 5px; /* 右上角圆角 */\n"
"    min-width: 100px; /* 标签页最小宽度 */\n"
"    min-height: 30px; /* 标签页最小高度 */\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(255, 255, 255); /* 选中标签页的背景颜色 */\n"
"    color: rgb(0, 0, 0); /* 选中标签页的字体颜色 */\n"
"}\n"
"QTabWidget {\n"
"    background-color: rgb(240, 240, 240); /* 主体背景颜色 */\n"
"    font-family: 微软雅黑; /* 字体类型 */\n"
"    font-size: 18px; /* 字体大小 */\n"
"    color: rgb(50, 50, 50); /* 字体颜色 */\n"
"}\n"
"")
        self.tabCi.setObjectName("tabCi")
        self.tabCiPage1 = QtWidgets.QWidget()
        self.tabCiPage1.setGeometry(QtCore.QRect(0, 0, 461, 367))
        self.tabCiPage1.setObjectName("tabCiPage1")
        self.textLevelDiv = QtWidgets.QTextEdit(self.tabCiPage1)
        self.textLevelDiv.setGeometry(QtCore.QRect(160, 30, 281, 221))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.textLevelDiv.setFont(font)
        self.textLevelDiv.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px")
        self.textLevelDiv.setObjectName("textLevelDiv")
        self.label_3 = QtWidgets.QLabel(self.tabCiPage1)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 151, 51))
        self.label_3.setStyleSheet("#label_3{\n"
"    border-radius:4px;\n"
"    background-color: transparent;\n"
"    font: 18pt \"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.btnCancel = QtWidgets.QPushButton(self.tabCiPage1)
        self.btnCancel.setGeometry(QtCore.QRect(270, 290, 121, 71))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("#btnCancel{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#btnCancel:hover{\n"
"    icon:url(:/images/error_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#btnCancel:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/error.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon)
        self.btnCancel.setObjectName("btnCancel")
        self.btnOk = QtWidgets.QPushButton(self.tabCiPage1)
        self.btnOk.setGeometry(QtCore.QRect(50, 290, 121, 71))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.btnOk.setFont(font)
        self.btnOk.setStyleSheet("#btnOk{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#btnOk:hover{\n"
"    icon:url(:/images/correct_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#btnOk:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/correct .svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOk.setIcon(icon1)
        self.btnOk.setObjectName("btnOk")
        self.tip2 = QtWidgets.QPushButton(self.tabCiPage1)
        self.tip2.setGeometry(QtCore.QRect(10, 10, 21, 28))
        self.tip2.setStyleSheet("#tip2{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#tip2:hover{\n"
"    icon:url(:/images/help_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#tip2:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.tip2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tip2.setIcon(icon2)
        self.tip2.setObjectName("tip2")
        self.tabCi.addItem(self.tabCiPage1, "")
        self.tabCiPage2 = QtWidgets.QWidget()
        self.tabCiPage2.setGeometry(QtCore.QRect(0, 0, 461, 367))
        self.tabCiPage2.setObjectName("tabCiPage2")
        self.label_4 = QtWidgets.QLabel(self.tabCiPage2)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 151, 51))
        self.label_4.setStyleSheet("#label_4{\n"
"    border-radius:4px;\n"
"    background-color: transparent;\n"
"    font: 18pt \"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.textCiRoot = QtWidgets.QTextBrowser(self.tabCiPage2)
        self.textCiRoot.setEnabled(False)
        self.textCiRoot.setGeometry(QtCore.QRect(170, 70, 256, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.textCiRoot.setFont(font)
        self.textCiRoot.setObjectName("textCiRoot")
        self.btnImpConfig = QtWidgets.QPushButton(self.tabCiPage2)
        self.btnImpConfig.setGeometry(QtCore.QRect(20, 180, 211, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.btnImpConfig.setFont(font)
        self.btnImpConfig.setStyleSheet("#btnImpConfig{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#btnImpConfig:hover{\n"
"    icon:url(:/images/inbox-out_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#btnImpConfig:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/inbox-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnImpConfig.setIcon(icon3)
        self.btnImpConfig.setObjectName("btnImpConfig")
        self.btnResetCi = QtWidgets.QPushButton(self.tabCiPage2)
        self.btnResetCi.setGeometry(QtCore.QRect(310, 180, 111, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.btnResetCi.setFont(font)
        self.btnResetCi.setStyleSheet("#btnResetCi{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#btnResetCi:hover{\n"
"    icon:url(:/images/refresh_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#btnResetCi:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnResetCi.setIcon(icon4)
        self.btnResetCi.setObjectName("btnResetCi")
        self.btnOkZ = QtWidgets.QPushButton(self.tabCiPage2)
        self.btnOkZ.setGeometry(QtCore.QRect(30, 290, 191, 61))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.btnOkZ.setFont(font)
        self.btnOkZ.setStyleSheet("#btnOkZ{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#btnOkZ:hover{\n"
"    icon:url(:/images/correct_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#btnOkZ:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.btnOkZ.setIcon(icon1)
        self.btnOkZ.setObjectName("btnOkZ")
        self.btnCancelZ = QtWidgets.QPushButton(self.tabCiPage2)
        self.btnCancelZ.setGeometry(QtCore.QRect(262, 290, 181, 61))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.btnCancelZ.setFont(font)
        self.btnCancelZ.setStyleSheet("#btnCancelZ{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#btnCancelZ:hover{\n"
"    icon:url(:/images/error_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#btnCancelZ:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.btnCancelZ.setIcon(icon)
        self.btnCancelZ.setObjectName("btnCancelZ")
        self.tip3 = QtWidgets.QPushButton(self.tabCiPage2)
        self.tip3.setGeometry(QtCore.QRect(10, 0, 31, 28))
        self.tip3.setStyleSheet("#tip3{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#tip3:hover{\n"
"    icon:url(:/images/help_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#tip3:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.tip3.setText("")
        self.tip3.setIcon(icon2)
        self.tip3.setObjectName("tip3")
        self.tabCi.addItem(self.tabCiPage2, "")
        self.tip1 = QtWidgets.QPushButton(self.top)
        self.tip1.setGeometry(QtCore.QRect(470, 130, 31, 28))
        self.tip1.setStyleSheet("#tip1{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#tip1:hover{\n"
"    icon:url(:/images/help_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#tip1:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.tip1.setText("")
        self.tip1.setIcon(icon2)
        self.tip1.setObjectName("tip1")
        self.top.raise_()
        self.textViewDiv.raise_()
        self.textCount.raise_()
        self.label_2.raise_()
        self.label.raise_()

        self.retranslateUi(buildGraular)
        self.btnOk.clicked.connect(buildGraular.okConfig) # type: ignore
        self.btnCancel.clicked.connect(buildGraular.cancelWindow) # type: ignore
        self.btnImpConfig.clicked.connect(buildGraular.impCi) # type: ignore
        self.btnResetCi.clicked.connect(buildGraular.resetCi) # type: ignore
        self.btnOkZ.clicked.connect(buildGraular.okCi) # type: ignore
        self.btnCancelZ.clicked.connect(buildGraular.cancelWindow) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(buildGraular)

    def retranslateUi(self, buildGraular):
        _translate = QtCore.QCoreApplication.translate
        buildGraular.setWindowTitle(_translate("buildGraular", "粒结构建立"))
        self.label.setText(_translate("buildGraular", "判断属性:"))
        self.label_2.setText(_translate("buildGraular", "视图划分:"))
        self.textLevelDiv.setHtml(_translate("buildGraular", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("buildGraular", "层次构建："))
        self.btnCancel.setText(_translate("buildGraular", "取消"))
        self.btnOk.setText(_translate("buildGraular", "确定"))
        self.tip2.setToolTip(_translate("buildGraular", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">属性中的层次构建格式</span></p><p><span style=\" font-size:12pt; font-weight:600;\">假设判断属性为6</span></p><p><span style=\" font-size:12pt; font-weight:600;\">视图的划分为1,2,3</span></p><p><span style=\" font-size:12pt; font-weight:600;\">层次构建的输入格式：</span></p><p><span style=\" font-size:12pt; font-weight:600;\">1</span></p><p><span style=\" font-size:12pt; font-weight:600;\">1,1</span></p><p><span style=\" font-size:12pt; font-weight:600;\">1,1,1</span></p><p><span style=\" font-size:12pt; font-weight:600;\">以回车来分割不同的视图，以逗号来分割不同视图中的层次划分，逗号是英文格式的逗号。</span></p></body></html>"))
        self.tabCi.setItemText(self.tabCi.indexOf(self.tabCiPage1), _translate("buildGraular", "属性"))
        self.label_4.setText(_translate("buildGraular", "层次构建："))
        self.btnImpConfig.setText(_translate("buildGraular", "导入配置文件"))
        self.btnResetCi.setText(_translate("buildGraular", "重置"))
        self.btnOkZ.setText(_translate("buildGraular", "确定"))
        self.btnCancelZ.setText(_translate("buildGraular", "取消"))
        self.tip3.setToolTip(_translate("buildGraular", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">根据属性值的层次构建主要是针对的连续值的情况</span></p><p><span style=\" font-size:12pt; font-weight:600;\">导入的配置文件必须是.txt形式的文件</span></p><p><span style=\" font-size:12pt; font-weight:600;\">假设判断属性为6 </span></p><p><span style=\" font-size:12pt; font-weight:600;\">视图的划分为2,2,2</span></p><p><span style=\" font-size:12pt; font-weight:600;\">导入的配置文件尾cs.txt</span></p><p><span style=\" font-size:12pt; font-weight:600;\">其中cs.txt的配置文件如下：</span></p><p><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#a9b7c6; background-color:#2b2b2b;\">0-0 | 1-1</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#a9b7c6;\"><br/>0-89 | 90-120 | 120-250<br/>----<br/>0-0 | 1-1<br/>0-5.9 | 6-7.5 | 7.5-25<br/>----<br/>0-50 | 51-250<br/>18-30 | 31-40 | 41-50 | 51-65 | 66-100</span></p><p><span style=\" font-size:12pt; font-weight:600;\">其中每一行代表层次的构建，|代表将连续值按照属性值范围进行转化，0-89代表[0,89]前后都是闭区间，----代表不同视图之间的划分。</span></p><p><br/></p><p><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:10pt; font-weight:600; color:#a9b7c6;\"><br/></span></p></body></html>"))
        self.tabCi.setItemText(self.tabCi.indexOf(self.tabCiPage2), _translate("buildGraular", "属性值"))
        self.tip1.setToolTip(_translate("buildGraular", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">假设判断属性为6</span></p><p><span style=\" font-size:12pt; font-weight:600;\">输入格式：1,2,3</span></p><p><span style=\" font-size:12pt; font-weight:600;\">代表有三个视图，第一个视图有1个判断属性，第二个视图有2个判断属性，第三个视图有3个判断属性，其中视图之间用英文，进行分割。</span></p></body></html>"))

