# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image_rc

class Ui_MainUI(object):
    def setupUi(self, MainUI):
        MainUI.setObjectName("MainUI")
        MainUI.setEnabled(True)
        MainUI.resize(1219, 557)
        MainUI.setStyleSheet("")
        self.textView_1 = QtWidgets.QTextEdit(MainUI)
        self.textView_1.setEnabled(False)
        self.textView_1.setGeometry(QtCore.QRect(410, 30, 240, 51))
        self.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.MSWindowsFixedSizeDialogHint)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.textView_1.setFont(font)
        self.textView_1.setStyleSheet("border:2px solid rgb(186,186,186);\n"
"border-radius:10px\n"
"")
        self.textView_1.setObjectName("textView_1")
        self.label_2 = QtWidgets.QLabel(MainUI)
        self.label_2.setGeometry(QtCore.QRect(300, 10, 91, 87))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("#label_2{\n"
"    border-radius:4px;\n"
"    background-color: transparent;\n"
"    font: 18pt \"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.tabWidget = QtWidgets.QTabWidget(MainUI)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(270, 110, 971, 451))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("\n"
"QTabWidget::tab-bar { \n"
"    alignment: center; \n"
"} \n"
"QTabBar::tab:hover{ \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: transparent;\n"
"}\n"
"QTabWidget::pane{ \n"
"    border:none;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: transparent; /* 标签页背景颜色 */\n"
"    font-family: 微软雅黑; /* 标签页字体类型 */\n"
"    font-size: 24px; /* 标签页字体大小 */\n"
"    color: rgb(255, 255, 255); /* 标签页字体颜色 */\n"
"    padding: 10px; /* 内边距 */\n"
"    border: 1px solid rgb(150, 150, 150); /* 边框 */\n"
"    border-top-left-radius: 5px; /* 左上角圆角 */\n"
"    border-top-right-radius: 5px; /* 右上角圆角 */\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: transparent; /* 选中标签页的背景颜色 */\n"
"    color: rgb(0, 0, 0); /* 选中标签页的字体颜色 */\n"
"}\n"
"*{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.textShow_1 = QtWidgets.QTextEdit(self.tab)
        self.textShow_1.setEnabled(False)
        self.textShow_1.setGeometry(QtCore.QRect(40, 10, 891, 371))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textShow_1.setFont(font)
        self.textShow_1.setStyleSheet("\n"
"background: transparent;  \n"
"color: rgb(0, 0, 0);  \n"
"")
        self.textShow_1.setObjectName("textShow_1")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textShow_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textShow_2.setEnabled(False)
        self.textShow_2.setGeometry(QtCore.QRect(40, 10, 901, 371))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textShow_2.setFont(font)
        self.textShow_2.setStyleSheet("\n"
"background: transparent;  \n"
"color: rgb(0, 0, 0);  \n"
"")
        self.textShow_2.setObjectName("textShow_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textShow_3 = QtWidgets.QTextEdit(self.tab_3)
        self.textShow_3.setEnabled(False)
        self.textShow_3.setGeometry(QtCore.QRect(40, 10, 901, 371))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.textShow_3.setFont(font)
        self.textShow_3.setObjectName("textShow_3")
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setGeometry(QtCore.QRect(-41, -160, 991, 561))
        self.frame_2.setStyleSheet("\n"
"background: transparent;  \n"
"color: rgb(0, 0, 0);  \n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.textShow_3.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.frame = QtWidgets.QFrame(MainUI)
        self.frame.setGeometry(QtCore.QRect(0, 0, 231, 561))
        self.frame.setStyleSheet("\n"
"background-image: url(:/images/bg01_cs01.png);\n"
"  background-position: center;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ahu01 = QtWidgets.QLabel(self.frame)
        self.ahu01.setGeometry(QtCore.QRect(60, 440, 111, 111))
        self.ahu01.setStyleSheet("    background: transparent;  \n"
"    color: white;  ")
        self.ahu01.setText("")
        self.ahu01.setPixmap(QtGui.QPixmap(":/images/ahu_02.jpg"))
        self.ahu01.setObjectName("ahu01")
        self.gridFrame = QtWidgets.QFrame(MainUI)
        self.gridFrame.setGeometry(QtCore.QRect(10, 0, 221, 461))
        self.gridFrame.setStyleSheet("")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.help = QtWidgets.QPushButton(self.gridFrame)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.help.setFont(font)
        self.help.setStyleSheet("#help{\n"
"    background: transparent;  \n"
"    color: rgb(0, 0, 0);  \n"
"    text-align: left;\n"
"    border-radius:10px\n"
"}\n"
"#help:hover{\n"
"    icon:url(:/images/help_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#help:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help.setIcon(icon)
        self.help.setObjectName("help")
        self.gridLayout.addWidget(self.help, 5, 0, 1, 1)
        self.buildGranular = QtWidgets.QPushButton(self.gridFrame)
        self.buildGranular.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.buildGranular.setFont(font)
        self.buildGranular.setStyleSheet("#buildGranular{\n"
"text-align: left;\n"
"    \n"
"    background-color: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#buildGranular:hover{\n"
"    icon:url(:/images/newlybuild_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#buildGranular:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/newlybuild.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buildGranular.setIcon(icon1)
        self.buildGranular.setObjectName("buildGranular")
        self.gridLayout.addWidget(self.buildGranular, 2, 0, 1, 1)
        self.optGranular = QtWidgets.QPushButton(self.gridFrame)
        self.optGranular.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.optGranular.setFont(font)
        self.optGranular.setStyleSheet("#optGranular{\n"
"text-align: left;\n"
"    \n"
"    background: transparent;  \n"
"    color: rgb(0, 0, 0);  \n"
"    border-radius:10px\n"
"}\n"
"#optGranular:hover{\n"
"    icon:url(:/images/smart-optimization_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#optGranular:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/smart-optimization.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.optGranular.setIcon(icon2)
        self.optGranular.setObjectName("optGranular")
        self.gridLayout.addWidget(self.optGranular, 3, 0, 1, 1)
        self.pushProblems = QtWidgets.QPushButton(self.gridFrame)
        self.pushProblems.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.pushProblems.setFont(font)
        self.pushProblems.setStyleSheet("#pushProblems{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#pushProblems:hover{\n"
"    icon:url(:/images/help_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#pushProblems:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/tips.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushProblems.setIcon(icon3)
        self.pushProblems.setObjectName("pushProblems")
        self.gridLayout.addWidget(self.pushProblems, 4, 0, 1, 1)
        self.pushView_1 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushView_1.sizePolicy().hasHeightForWidth())
        self.pushView_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.pushView_1.setFont(font)
        self.pushView_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushView_1.setStyleSheet("#pushView_1{\n"
"    text-align: left;\n"
"    background-color: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#pushView_1:hover{\n"
"    icon:url(:/images/inbox-out_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#pushView_1:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/inbox-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/images/inbox-out_hover.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(":/images/inbox-out_hover.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(":/images/inbox-out.svg"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/images/inbox-out_hover.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushView_1.setIcon(icon4)
        self.pushView_1.setObjectName("pushView_1")
        self.gridLayout.addWidget(self.pushView_1, 0, 0, 1, 1)
        self.btnConfig = QtWidgets.QPushButton(self.gridFrame)
        self.btnConfig.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.btnConfig.setFont(font)
        self.btnConfig.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnConfig.setStyleSheet("#btnConfig{\n"
"text-align: left;\n"
"    \n"
"    background-color: transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#btnConfig:hover{\n"
"    icon:url(:/images/file-settings-one_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color:transparent;\n"
"}\n"
"#btnConfig:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/file-settings-one.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConfig.setIcon(icon5)
        self.btnConfig.setObjectName("btnConfig")
        self.gridLayout.addWidget(self.btnConfig, 1, 0, 1, 1)
        self.bg = QtWidgets.QFrame(MainUI)
        self.bg.setGeometry(QtCore.QRect(230, 0, 991, 561))
        self.bg.setStyleSheet("background-image: url(:/images/bg01_cs02.png);\n"
"background-position: center;")
        self.bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bg.setObjectName("bg")
        self.selectAlgorithm = QtWidgets.QComboBox(self.bg)
        self.selectAlgorithm.setEnabled(True)
        self.selectAlgorithm.setGeometry(QtCore.QRect(450, 60, 251, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.selectAlgorithm.setFont(font)
        self.selectAlgorithm.setStyleSheet("#selectAlgorithm{\n"
"    border-radius:11px;\n"
"    background-color: rgb(184, 184, 184);\n"
"    color: rgb(56,56,56);\n"
"    background: transparent;  \n"
"}\n"
"#selectAlgorithm:hover{\n"
"    border-radius:0px;\n"
"    background-color: rgb(184, 184, 184);\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"    color: rgb(56,56,56);\n"
"    background: transparent;  \n"
"}\n"
"#selectAlgorithm::drop-down{\n"
"    border-top-right-radius:5px;\n"
"    border-bottom-right-radius:5px;\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(40,40,40);\n"
"    min-width:30px;\n"
"    background: transparent;  \n"
"}\n"
"#selectAlgorithm::down-arrow{\n"
"    image: url(:/images/rows.png);\n"
"    height:28px;\n"
"    width:28px;\n"
"}\n"
"#selectAlgorithm QComboBox{\n"
"    font-size:20px;\n"
"    font-weight:bold;\n"
"background: transparent;  \n"
"}\n"
"#selectAlgorithm QComboBox::item{\n"
"    color: rgb(40, 40, 40);\n"
"    height:30px;\n"
"    selection-color: rgb(186,186,186);\n"
"    background-color:rgb(80, 80, 80);\n"
"}\n"
"\n"
"")
        self.selectAlgorithm.setPlaceholderText("")
        self.selectAlgorithm.setObjectName("selectAlgorithm")
        self.selectAlgorithm.addItem("")
        self.selectAlgorithm.addItem("")
        self.selectAlgorithm_2 = QtWidgets.QComboBox(self.bg)
        self.selectAlgorithm_2.setEnabled(True)
        self.selectAlgorithm_2.setGeometry(QtCore.QRect(450, 10, 251, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.selectAlgorithm_2.setFont(font)
        self.selectAlgorithm_2.setStyleSheet(" \n"
"#selectAlgorithm_2{\n"
"    border-radius:11px;\n"
"    background-color: rgb(184, 184, 184);\n"
"    color: rgb(56,56,56);\n"
"background: transparent;  \n"
"}\n"
"#selectAlgorithm_2:hover{\n"
"    border-radius:0px;\n"
"    background-color: rgb(184, 184, 184);\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"    color: rgb(56,56,56);\n"
"    background: transparent;  \n"
"}\n"
"#selectAlgorithm_2::drop-down{\n"
"    border-top-right-radius:5px;\n"
"    border-bottom-right-radius:5px;\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(40,40,40);\n"
"    min-width:30px;\n"
"    background: transparent;  \n"
"}\n"
"#selectAlgorithm_2::down-arrow{\n"
"    image: url(images/rows.png);\n"
"    height:28px;\n"
"    width:28px;\n"
"}\n"
"#selectAlgorithm_2 QComboBox{\n"
"    font-size:20px;\n"
"    font-weight:bold;\n"
"}\n"
"#selectAlgorithm_2 QComboBox::item{\n"
"    color: rgb(40, 40, 40);\n"
"    height:30px;\n"
"    selection-color: rgb(186,186,186);\n"
"    background-color:rgb(80, 80, 80);\n"
"    background: transparent;  \n"
"}\n"
"\n"
"\n"
"")
        self.selectAlgorithm_2.setPlaceholderText("")
        self.selectAlgorithm_2.setObjectName("selectAlgorithm_2")
        self.selectAlgorithm_2.addItem("")
        self.selectAlgorithm_2.addItem("")
        self.selectAlgorithm_2.addItem("")
        self.selectAlgorithm_2.addItem("")
        self.resetView_1 = QtWidgets.QPushButton(self.bg)
        self.resetView_1.setGeometry(QtCore.QRect(850, 30, 121, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.resetView_1.setFont(font)
        self.resetView_1.setStyleSheet("#resetView_1{\n"
"    background-color:transparent;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#resetView_1:hover{\n"
"    icon:url(images/refresh_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#resetView_1:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetView_1.setIcon(icon6)
        self.resetView_1.setObjectName("resetView_1")
        self.tip3 = QtWidgets.QPushButton(self.bg)
        self.tip3.setGeometry(QtCore.QRect(40, 40, 21, 28))
        self.tip3.setStyleSheet("#tip3{\n"
"    background: transparent;  \n"
"    color: white;  \n"
"    text-align: left;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:10px\n"
"}\n"
"#tip3:hover{\n"
"    icon:url(:/images/help_hover.svg);\n"
"    color: rgb(144, 19, 158);\n"
"    background-color: transparent;\n"
"}\n"
"#tip3:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px\n"
"}\n"
"")
        self.tip3.setText("")
        self.tip3.setIcon(icon)
        self.tip3.setObjectName("tip3")
        self.verticalFrame = QtWidgets.QFrame(self.bg)
        self.verticalFrame.setGeometry(QtCore.QRect(720, 0, 141, 101))
        self.verticalFrame.setStyleSheet("\n"
"background: transparent;  \n"
"color: rgb(0, 0, 0);  \n"
"")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.r1 = QtWidgets.QRadioButton(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.r1.setFont(font)
        self.r1.setObjectName("r1")
        self.verticalLayout.addWidget(self.r1)
        self.r1.setChecked(True)
        self.r2 = QtWidgets.QRadioButton(self.verticalFrame)
        self.r2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.r2.setFont(font)
        self.r2.setObjectName("r2")
        self.verticalLayout.addWidget(self.r2)
        self.radioButton = QtWidgets.QRadioButton(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.verticalFrame.raise_()
        self.selectAlgorithm.raise_()
        self.selectAlgorithm_2.raise_()
        self.resetView_1.raise_()
        self.tip3.raise_()
        self.bg.raise_()
        self.frame.raise_()
        self.gridFrame.raise_()
        self.textView_1.raise_()
        self.label_2.raise_()
        self.tabWidget.raise_()

        self.retranslateUi(MainUI)
        self.tabWidget.setCurrentIndex(0)
        self.resetView_1.clicked.connect(MainUI.reSetView) # type: ignore
        self.pushView_1.clicked.connect(MainUI.importView) # type: ignore
        self.btnConfig.clicked.connect(MainUI.configGranular) # type: ignore
        self.buildGranular.clicked.connect(MainUI.buildGranularW) # type: ignore
        self.optGranular.clicked.connect(MainUI.optGranularW) # type: ignore
        self.pushProblems.clicked.connect(MainUI.resolveProblemsW) # type: ignore
        self.help.clicked.connect(MainUI.helps) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainUI)

    def retranslateUi(self, MainUI):
        _translate = QtCore.QCoreApplication.translate
        MainUI.setWindowTitle(_translate("MainUI", "基于粒计算的多模态数据多粒度融合仿真系统"))
        self.label_2.setText(_translate("MainUI", "数据集:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainUI", "粒结构建立"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainUI", "粒结构优化"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainUI", "问题求解"))
        self.help.setText(_translate("MainUI", "帮助文档"))
        self.buildGranular.setText(_translate("MainUI", "粒结构建立"))
        self.optGranular.setText(_translate("MainUI", "粒结构优化"))
        self.pushProblems.setText(_translate("MainUI", "问题求解"))
        self.pushView_1.setText(_translate("MainUI", "导入数据集"))
        self.btnConfig.setText(_translate("MainUI", "配置"))
        self.selectAlgorithm.setItemText(0, _translate("MainUI", "满意粒度层选择"))
        self.selectAlgorithm.setItemText(1, _translate("MainUI", "最优粒度层选择"))
        self.selectAlgorithm_2.setCurrentText(_translate("MainUI", "DecisionTree"))
        self.selectAlgorithm_2.setItemText(0, _translate("MainUI", "DecisionTree"))
        self.selectAlgorithm_2.setItemText(1, _translate("MainUI", "KNN"))
        self.selectAlgorithm_2.setItemText(2, _translate("MainUI", "SVC"))
        self.selectAlgorithm_2.setItemText(3, _translate("MainUI", "AdaBoost"))
        self.resetView_1.setText(_translate("MainUI", "重置"))
        self.tip3.setToolTip(_translate("MainUI", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">导入的文件必须是.csv格式的文件</span></p></body></html>"))
        self.r1.setText(_translate("MainUI", "属性拼接"))
        self.r2.setText(_translate("MainUI", "结果融合"))
        self.radioButton.setText(_translate("MainUI", "特征融合"))

